#!/usr/bin/env python3
"""Build eza's and nvim's icon config from data/icons.txt.

Usage: build-icons.py

Writes:
  data/eza-theme.yml   the filenames and extensions sections of an eza theme,
                       giving each entry its icon. The icons have no style, so
                       eza colors them like the file name (i.e. from LS_COLORS
                       and the rest of the theme).
  data/mini-icons.lua  a Lua module returning mini.icons' config (default,
                       directory, file, extension and filetype icons), the
                       colors of its highlight groups (one per color in
                       icons.txt), and the defaults (for e.g. neo-tree, since
                       mini.icons has no default for files with no extension).

A filetype gets the icon of an extension with that filetype (per Neovim's
filetype detection), preferring one named like the filetype, unless icons.txt
gives it one. The defaults in icons.txt should be eza's built-in ones, since its
theme can't change them; that's checked too.

Icons are written as escapes rather than characters, so the files are plain
ASCII. eza silently ignores a theme it can't parse, so the eza theme is checked
by running eza with it.
"""

import json
import os
import pathlib
import subprocess
import sys
import tempfile

import icons


EZA_THEME = icons.ROOT / "data/eza-theme.yml"
MINI_ICONS = icons.ROOT / "data/mini-icons.lua"
HEADER = "Generated by build-icons.py from data/icons.txt: edit that and\n" \
         "rerun the script rather than editing this file."


def yaml_escape(glyph):
  code = ord(glyph)
  return f"\\u{code:04X}" if code <= 0xFFFF else f"\\U{code:08X}"


def lua_string(text):
  return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def highlight_group(color):
  """The highlight group for a color, e.g. IconsVimGreen for vim-green."""
  return "Icons" + "".join(part.capitalize() for part in color.split("-"))


def entries_by_kind(entries, glyphs):
  """{kind: {name: (glyph, color)}}, sorted by name."""
  result = {kind: {} for kind in (*icons.KINDS, "filetype")}
  for kind, name, icon, color in sorted(entries, key=lambda e: e[1].lower()):
    result[kind][name] = (glyphs.glyph(icon), color)
  return result


def filetypes(by_kind, ft_extension):
  """Each filetype's icon: from icons.txt if it has one, else that of an
  extension with the filetype, preferring one named like it (e.g. sh for the
  sh filetype) and otherwise the first. Also returns the filetypes whose
  extensions have different icons, where one was chosen."""
  candidates = {}
  for ext, icon in by_kind["ext"].items():
    filetype = ft_extension.get(ext)
    if filetype:
      candidates.setdefault(filetype, []).append((ext, icon))
  result, ambiguous = {}, []
  for filetype, exts in sorted(candidates.items()):
    named = [icon for ext, icon in exts if ext == filetype]
    result[filetype] = named[0] if named else exts[0][1]
    if not named and len({icon for _, icon in exts}) > 1:
      ambiguous.append(filetype)
  result.update(by_kind["filetype"])
  return dict(sorted(result.items())), [f for f in ambiguous
                                        if f not in by_kind["filetype"]]


def eza_theme(by_kind):
  # eza's theme matches directories by name in its filenames section too, so
  # it can't tell a directory and a file with the same name apart: use the
  # directory's icon, since that's more common.
  filenames = dict(by_kind["file"])
  clashes = sorted(name for name in by_kind["dir"] if name in filenames)
  filenames.update(by_kind["dir"])
  lines = ["# " + line for line in HEADER.splitlines()] + ["", "filenames:"]
  lines += [f"  {json.dumps(name, ensure_ascii=False)}: "
            f"{{icon: {{glyph: \"{yaml_escape(glyph)}\"}}}}"
            for name, (glyph, _) in sorted(filenames.items(),
                                           key=lambda item: item[0].lower())]
  lines.append("extensions:")
  lines += [f"  {json.dumps(name, ensure_ascii=False)}: "
            f"{{icon: {{glyph: \"{yaml_escape(glyph)}\"}}}}"
            for name, (glyph, _) in by_kind["ext"].items()]
  return "\n".join(lines) + "\n", clashes


def check_eza_theme(text, by_kind):
  """Check eza applies the theme, by listing a file with one of its
  extensions."""
  ext, (glyph, _) = next(iter(by_kind["ext"].items()))
  with tempfile.TemporaryDirectory() as tmp:
    (pathlib.Path(tmp) / "theme.yml").write_text(text, encoding="utf-8")
    sample = pathlib.Path(tmp, "sample")
    sample.mkdir()
    (sample / f"x.{ext}").touch()
    out = subprocess.run(
        ["eza", "-1", "--icons=always", "--color=never", str(sample)],
        capture_output=True, text=True, check=True, stdin=subprocess.DEVNULL,
        env={**os.environ, "EZA_CONFIG_DIR": tmp}).stdout
  if not out.startswith(glyph):
    icons.fail(f"eza didn't apply {EZA_THEME.name} (e.g. to x.{ext}); "
               "it ignores a theme it can't parse")


def lua_icon(glyph, color):
  return f"{{glyph = '\\u{{{ord(glyph):x}}}', hl = '{highlight_group(color)}'}}"


def mini_icons(by_kind, filetype_icons, defaults, palette):
  lines = ["-- " + line for line in HEADER.splitlines()]
  lines += ["return {",
            "  -- The colors of the highlight groups the icons use.",
            "  highlights = {"]
  lines += [f"    {highlight_group(color)} = {lua_string(hex_)},"
            for color, hex_ in palette.items()]
  lines += ["  },",
            "  -- Icons for files with an extension nothing knows (file),",
            "  -- files with no extension (noext) and directories (dir).",
            "  defaults = {"]
  lines += [f"    {kind} = {lua_icon(*defaults[kind])},"
            for kind in icons.DEFAULTS]
  lines += ["  },",
            "  -- mini.icons' defaults, by category (it has no default for",
            "  -- files with no extension).",
            "  default = {",
            f"    directory = {lua_icon(*defaults['dir'])},",
            f"    extension = {lua_icon(*defaults['file'])},",
            f"    file = {lua_icon(*defaults['file'])},",
            f"    filetype = {lua_icon(*defaults['file'])},",
            "  },"]
  for section, entries in (("directory", by_kind["dir"]),
                           ("file", by_kind["file"]),
                           ("extension", by_kind["ext"]),
                           ("filetype", filetype_icons)):
    lines.append(f"  {section} = {{")
    lines += [f"    [{lua_string(name)}] = {lua_icon(glyph, color)},"
              for name, (glyph, color) in entries.items()]
    lines.append("  },")
  lines.append("}")
  return "\n".join(lines) + "\n"


def main():
  if len(sys.argv) > 1:
    sys.exit(__doc__)
  glyphs = icons.Glyphs(refresh=False)
  palette, entries, defaults = icons.read_icons(glyphs)
  by_kind = entries_by_kind(entries, glyphs)
  defaults = {kind: (glyphs.glyph(icon), color)
              for kind, (icon, color) in defaults.items()}

  # The defaults should be eza's, which its theme can't change.
  builtin = icons.Eza(refresh=False).builtin_defaults
  differ = [kind for kind in icons.DEFAULTS
            if defaults[kind][0] != builtin[kind]]
  if differ:
    icons.fail("these defaults in data/icons.txt aren't eza's built-in ones, "
               "which its theme can't change: " + ", ".join(
                   f"{kind} (eza: {glyphs.name(builtin[kind])})"
                   for kind in differ))

  filetype_icons, ambiguous = filetypes(
      by_kind, icons.MiniIcons(refresh=False).ft_extension)

  theme, clashes = eza_theme(by_kind)
  check_eza_theme(theme, by_kind)
  EZA_THEME.write_text(theme, encoding="utf-8")
  MINI_ICONS.write_text(mini_icons(by_kind, filetype_icons, defaults, palette),
                        encoding="utf-8")

  counts = ", ".join(f"{len(by_kind[kind])} {icons.TITLES[kind].lower()}"
                     for kind in icons.KINDS)
  counts += f", {len(filetype_icons)} filetypes"
  print(f"Wrote {EZA_THEME.relative_to(icons.ROOT)} and "
        f"{MINI_ICONS.relative_to(icons.ROOT)} ({counts}).")
  if clashes:
    print("In the eza theme, these directories' icons are used for files of "
          "the same name: " + ", ".join(clashes))
  if ambiguous:
    print("These filetypes' extensions have different icons, so the first "
          "extension's was used (add a filetype line to choose): "
          + ", ".join(ambiguous))


if __name__ == "__main__":
  main()
