"""Build eza's and mini.icons' icon config from an icons file and its palette."""

import json
import pathlib

import bedeck.icons


HEADER = "Generated by `bedeck build`: edit the icons file and rebuild instead."

# mini.icons' categories, and the section of the icons file each one is.
CATEGORIES = {
  "directory": "dir",
  "file": "file",
  "extension": "ext",
  "filetype": "filetype",
}


def eza(icons: bedeck.icons.Icons) -> str:
  """The filenames and extensions sections of an eza theme. The icons have no
  style, so eza colors them like the file name."""
  # eza matches directories by name in filenames too, so a directory's icon
  # wins over that of a file with the same name.
  sections = {
    "filenames": bedeck.icons.by_name(icons["file"] | icons["dir"]),
    "extensions": icons["ext"],
  }
  lines = [f"# {HEADER}"]
  for section, entries in sections.items():
    lines.append(f"{section}:")
    for name, (glyph, _) in entries.items():
      code = ord(glyph)
      escape = f"\\u{code:04X}" if code <= 0xFFFF else f"\\U{code:08X}"
      lines.append(f'  {json.dumps(name)}: {{icon: {{glyph: "{escape}"}}}}')
  return "\n".join(lines) + "\n"


def highlight(color: str) -> str:
  """The highlight group for a color, e.g. IconsVimGreen for vim-green."""
  return "Icons" + color.title().replace("-", "")


def lua_icon(glyph: str, color: str) -> str:
  return f"{{glyph = '\\u{{{ord(glyph):x}}}', hl = '{highlight(color)}'}}"


def mini_icons(colors: dict[str, str], icons: bedeck.icons.Icons) -> str:
  """A Lua module returning mini.icons' config, the colors of its highlight
  groups and the defaults."""
  default = {name: lua_icon(*icon) for name, icon in icons["default"].items()}
  lines = [
    f"-- {HEADER}",
    "return {",
    "  -- The colors of the highlight groups the icons use.",
    "  highlights = {",
    *(f"    {highlight(name)} = '{value}'," for name, value in colors.items()),
    "  },",
    "  -- Icons for files with an extension nothing knows (file), files with",
    "  -- no extension (noext) and directories (dir).",
    "  defaults = {",
    *(f"    {name} = {default[name]}," for name in ("file", "noext", "dir")),
    "  },",
    "  -- mini.icons' defaults, by category (it has no default for files",
    "  -- with no extension).",
    "  default = {",
    f"    directory = {default['dir']},",
    f"    extension = {default['file']},",
    f"    file = {default['file']},",
    f"    filetype = {default['file']},",
    "  },",
  ]
  for category, section in CATEGORIES.items():
    lines.append(f"  {category} = {{")
    for name, icon in icons[section].items():
      name = name.replace("\\", "\\\\").replace("'", "\\'")
      lines.append(f"    ['{name}'] = {lua_icon(*icon)},")
    lines.append("  },")
  lines.append("}")
  return "\n".join(lines) + "\n"


def build(icons: pathlib.Path, palette: pathlib.Path, output: pathlib.Path):
  """Write eza.yml and mini-icons.lua to the output directory."""
  colors, data = bedeck.icons.load(icons, palette)
  output.mkdir(parents=True, exist_ok=True)
  files = {"eza.yml": eza(data), "mini-icons.lua": mini_icons(colors, data)}
  for name, text in files.items():
    (output / name).write_text(text, encoding="utf-8")
    print(f"Wrote {output / name}")
